name: Build App
on: workflow_dispatch
jobs:
    build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - name: Make the script files executable
          run: 
            chmod +x ./.github/build.sh
        - name: Run script
          run: 
            ./.github/build.sh
