name: Build App
on: workflow_dispatch
jobs:
    build:
      runs-on: macos-latest
      steps:
        - uses: maxim-lobanov/setup-xcode@v1
          with: xcode-version: '15.0.1'
        - name: Make the script files executable
          run: 
            chmod +x ./.github/build.sh
        - name: Run script
          run: 
            ./.github/build.sh